fix: DOS-1413 error while resume PULL transfer from provider
Cofinity-X/contrib-connector pull request #1
Opened 2024-11-21 08:38 UTC by AndrYurk

What this PR changes/adds
Adds a "SUSPENDED" state to the list of allowed states to be started consumer

Why it does that
To allow the provider resume the transfer without exceptions.

Further notes
To make possible create e2e test by provider commands, method awaitTransferToBeInState from TransferEndToEndTestBase was unified.

Linked Issue(s)

Part of Cofinity-X https://cofinity-x.atlassian.net/browse/DOS-1413
Part of upstream https://github.com/eclipse-edc/Connector/issues/4591

2024-11-21 12:48 UTC, ndr-brt commented on system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndTestBase.java
> +    protected void awaitTransferToBeInState(TransferEndToEndParticipant participant, String transferProcessId, TransferProcessStates state) {
I would put this method in the `Participant` class, so it will be directly available for every participant instance

2024-11-21 12:56 UTC, ndr-brt reviewed
Looks good, just 2 nits about testing, but for the rest it could be ready to go. :rocket: 
Let's see how it appears after applying the suggestion.

2024-11-21 12:56 UTC, ndr-brt commented on spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcessTest.java
> +        assertThat(process.getDataPlaneId()).isNull();
these lines are the same as the ones at 100:102.
my proposal would be to extract a (parameterized) test that asserts that the "transitionStarted" method for consumer won't set the dataPlaneId, both coming from `STARTING` and  `SUSPENDED`, so the assertion can be removed from this test (that's already too big, I guess something inherited from the early days of edc)

2024-11-22 08:51 UTC, AndrYurk commented
@ndr-brt  PR has been updated, please review

2024-11-22 12:43 UTC, ndr-brt requested changes
almost there

2024-11-22 12:43 UTC, ndr-brt commented on system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/TransferEndToEndParticipant.java
> +    protected void awaitTransferToBeInState(String transferProcessId, TransferProcessStates state) {
this can be pulled up to `Participant` so eventually other tests can benefit from it.

2024-11-22 12:43 UTC, ndr-brt commented on spi/control-plane/transfer-spi/src/test/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcessTest.java
> +        switch (state) {
conditions in tests are not a good practice because they can lead to hard to read errors plus they make the test less understandable.
My previous comment was only about testing that the `dataPlaneId` doesn't get set after `transitionStarted` when transfer is `CONSUMER` both when the current state is `STARTING` or `SUSPENDED`.

e.g.:
```java
    @ParameterizedTest
    @EnumSource(value = TransferProcessStates.class, mode = INCLUDE, names = { "STARTING", "SUSPENDED" })
    void shouldNotSetDataPlaneIdOnStart_whenTransferIsConsumer(TransferProcessStates fromState) {
        var process = TransferProcess.Builder.newInstance()
                .id(UUID.randomUUID().toString()).type(CONSUMER)
                .state(fromState.code())
                .build();

        process.transitionStarted("dataPlaneId");

        assertThat(process.stateAsString()).isEqualTo(STARTED.name());
        assertThat(process.getDataPlaneId()).isNull();
    }
```

at this point, the assertion about the getDataPlaneId on the `verifyConsumerTransitions` can be removed and the transitionSuspending/ed calls added as you done in the previous commit:

```java
    @Test
    void verifyConsumerTransitions() {
        var process = TransferProcess.Builder.newInstance().id(UUID.randomUUID().toString()).type(CONSUMER).build();

        process.transitionProvisioning(ResourceManifest.Builder.newInstance().build());
        process.transitionProvisioned();

        process.transitionRequesting();
        process.transitionRequested();

        assertThrows(IllegalStateException.class, process::transitionStarting, "STARTING is not a valid state for consumer");
        process.transitionStarted("dataPlaneId");

        process.transitionSuspending("suspension");
        process.transitionSuspended();

        process.transitionStarted("dataPlaneId");

        process.transitionCompleting();
        process.transitionCompleted();

        process.transitionDeprovisioning();
        process.transitionDeprovisioned();
    }
```

2024-11-26 07:54 UTC, ndr-brt approved these changes
From my side this is ready to be opened upstream :raised_hands:

2024-11-26 14:32 UTC, closed without merging